dist: trusty
before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended
script:
- bash build.sh
deploy:
  provider: releases
  prerelease: true
  file: build/handbook-compressed.pdf
  skip_cleanup: true
  on:
    all_branches: true
  token:
    secure: LxskO62Yz8/hJSRX7dsqccqb110+0xNnnwht5oOxnMOoyKN2SMpxVimxAaRUHeeOPisrTlvVgyUlt/Nm/K9+OCYsK4T5K7RvIMojY6NzHvcGp2n6tLa2PZ60sPdBHXGbaPXaJ8A1n40G2VOqLlswurhFjzKyvAtay9SSYCDYD5eoY+kQk5o7adNLHoa56QrN7Su1fMJoVL3Ztqnoi2D2l3o/GDB89exXHukliPLKJgxwMfYiS2gzakewQcIGio0J8RwVgM4282IAoQ9twjLlyNM1jyBKVDNRD/WZlA1259FS8D3+wynZa9jlV5hphRdhPwzelsrpUpXbuMCfbM7IMV4tRCxgjpTEPZ3aDpLf86B0U+ZsGJjvMfQWRf66uaQ+1BAX6iuCKs7tL/b1p6QPFWCl+Y+nYNHL0xr+7/lHmAkzVxN2HXEuzyOoRhIeaNTsYR1+H+1VmDvdM3PriWG2TQUf5kroZOi/UnQ11sKY3JajKthMaSiHWGq7aGU+46IDMaBxMrCueGj1U6AK2xGbKNSeFIoHUUlt6F4RNC/o6g/EyXqbJ3s+ribysa5mNMC8o/f7jo9iXhPdA3fpziyV61dhvvdY933p4E6PIZ9qox3ogw0i+Hl/tVnC25m03YsFiKZNB3R4fSBN+IRFJ07WUuA5hInzdM1erNvHs6sLGh0=

